name: Canvas → Notion sync

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes UTC
  push:
    paths:
      - "sync.py"
      - ".github/workflows/canvas-to-notion.yml"
      - "requirements.txt"

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    concurrency:
      group: canvas-to-notion
      cancel-in-progress: true

    # Make env available to ALL steps. Falls back to repo Variables if Secrets are empty.
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN || vars.NOTION_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID || vars.NOTION_DATABASE_ID }}
      CANVAS_BASE_URL: ${{ secrets.CANVAS_BASE_URL || vars.CANVAS_BASE_URL }}
      CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN || vars.CANVAS_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Just prints masked lengths to catch empty/mistyped secrets/variables.
      - name: Sanity-check env (lengths only)
        run: |
          echo "NOTION_TOKEN len: ${#NOTION_TOKEN}"
          echo "NOTION_DATABASE_ID len: ${#NOTION_DATABASE_ID}"
          echo "CANVAS_BASE_URL len: ${#CANVAS_BASE_URL}"
          echo "CANVAS_TOKEN len: ${#CANVAS_TOKEN}"

      - name: Run sync
        run: python sync.py
