name: Canvas → Notion sync

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes UTC
  push:
    paths:
      - "sync.py"
      - ".github/workflows/canvas-to-notion.yml"
      - "requirements.txt"

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    concurrency:
      group: canvas-to-notion
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          CANVAS_BASE_URL: ${{ secrets.CANVAS_BASE_URL }}
          CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN }}
        run: python sync.py
