name: Canvas → Notion Sync

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes; tweak as you like
  workflow_dispatch:
    inputs:
      lookahead_days:
        description: "How many days ahead to sync from Canvas (default 30)"
        required: false
        default: "30"

permissions:
  contents: read

concurrency:
  group: canvas-notion-sync
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # optional: quick visibility into what the runner sees
      - name: Debug repo contents
        run: |
          pwd
          find . -maxdepth 2 -type f -print

      - name: Run Canvas → Notion sync
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          CANVAS_API_BASE: ${{ secrets.CANVAS_API_BASE }}     # e.g., https://rutgers.instructure.com
          CANVAS_API_TOKEN: ${{ secrets.CANVAS_API_TOKEN }}
          CANVAS_LOOKAHEAD_DAYS: ${{ github.event.inputs.lookahead_days || '30' }}
        run: |
          python sync.py
